project:
  type: book

book:
  downloads: [docx, pdf]
  title: "Example Quarto Site for R"
  page-navigation: true
  site-url: https://pommevilla.github.io/r3-quarto-example
  repo-url: https://github.com/pommevilla/r3-quarto-example
  toc: true
  
  sidebar:
    collapse-level: 1
    style: "docked"
    align: "center"

  navbar:
    type: light
    title: "Example Quarto Site for R3"
    right:
      - text: "R3 @ R/Medicine"
        url: https://r3-rmedicine.netlify.app/
      - text: "Quarto docs"
        url: https://quarto.org
      
  chapters:
      - index.qmd
      - first.qmd
      - second.qmd
      - third.ipynb
      - four.qmd
      - example_sites.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - styles/styles.scss
    code-background: true
    number-sections: false
    code-tools:
      source: true
      
  pdf:
    code-background: true

  docx:
    toc: true
