project:
  type: book

execute:
  freeze: true
  
book:
  downloads: [docx, pdf]
  title: "Example Quarto Site for R"
  page-navigation: true
  site-url: https://pommevilla.github.io/r3-quarto-example
  repo-url: https://github.com/pommevilla/r3-quarto-example
  toc: true
  
  sidebar:
    style: "docked"
    align: left

  navbar:
    type: light
    title: "Example Quarto Site for R3"
    right:
      - text: "R3 @ R/Medicine"
        url: https://r3-rmedicine.netlify.app/
      - text: "Quarto docs"
        url: https://quarto.org
      
  chapters:
      - index.qmd
      - docs/first.qmd
      - docs/second.qmd
      - docs/third.ipynb
      - docs/four.qmd

bibliography: docs/references.bib

format:
  html:
    theme:
      - cosmo
      - styles/styles.scss
    code-background: true
    number-sections: false
    code-tools:
      source: true
      
  pdf:
    code-background: true

  docx:
    toc: true
