---
title: "Introduction"
---

This is an example Quarto project made for the Reproducible Research with R workshop at the R/Medicine conference on 8/25/2021. 

## Installing Quarto

In order to work with Quarto from your own computer, you'll need to install the Quarto CLI and a daily build of RStudio.

* You can download the latest version of the Quarto CLI from the [Quarto github](https://github.com/quarto-dev/quarto-cli/releases/latest). Select the appropriate version for your OS and run the installer.
* You can download a daily build of RStudio [here](https://dailies.rstudio.com/). The daily build has support for Quarto documents that isn't in the official release yet.

From here, you'll be able to render Quarto documents in RStudio just like you've been doing today.

For full installation instructions, see [the Quarto docs](https://quarto.org/docs/getting-started/installation.html).

## About this site

This is a Quarto `book` project. 
You're able to download the entire site as a single document by clicking the download button in the upper right hand corner. 

A Quarto project is a collection of documents (`qmd`, `md`, `Rmd`, and `ipynb` files) that are unified by a `_quarto.yml` file. This `_quarto.yml` file contains, among other things (from the docs):

* A way to render all or some of the files in a directory with a single command (e.g. quarto render myproject).
* A way to share YAML configuration across multiple documents.
* The ability to redirect output artifacts to another directory.
* The ability to freeze rendered output (i.e. don’t re-execute documents unless they have changed).

You can see the `_quarto.yml` for this site [here](https://github.com/pommevilla/r3-quarto-example/blob/main/_quarto.yml).

To learn more about Quarto projects, see the [Projects section](https://quarto.org/docs/projects/quarto-projects.html) of the docs.